import { getDefaultLanguageIds, getDefaultLanguagePackIds } from "./languagePackages";
import type { lotusPluginSettings } from "./types";

export const DEFAULT_GODBOLT_COMPILER_DEFAULTS: Record<string, string> = {
  "c": "cg161",
  "c++": "g161",
  "rust": "r1970",
  "go": "gl1260",
  "java": "java2501",
  "python": "python314",
  "javascript": "v8trunk",
  "typescript": "tsc_0_0_35_gc",
  "ruby": "ruby405",
  "ocaml": "ocaml5200",
  "llvm": "llctrunk",
  "assembly": "nasm301",
  "haskell": "ghc9122",
  "lua": "lua550",
  "perl": "perl5422",
  "lean": "lean_4_29_1",
};

export const DEFAULT_GODBOLT_OPTIONS_DEFAULTS: Record<string, string> = {
  "c": "-O2",
  "c++": "-O2 -std=c++20",
  "rust": "-O",
};

export const DEFAULT_SETTINGS: lotusPluginSettings = {
  enableLocalExecution: false,
  hasAcknowledgedExecutionRisk: false,
  preserveSourceMode: true,
  defaultTimeoutMs: 8000,
  workingDirectory: "",
  pythonExecutable: "python3",
  nodeExecutable: "node",
  typescriptMode: "ts-node",
  typescriptTranspilerExecutable: "ts-node",
  ocamlMode: "ocaml",
  ocamlExecutable: "ocaml",
  cExecutable: "gcc",
  cppExecutable: "g++",
  shellExecutable: "bash",
  rubyExecutable: "ruby",
  perlExecutable: "perl",
  luaExecutable: "lua",
  phpExecutable: "php",
  goExecutable: "go",
  rustExecutable: "rustc",
  haskellExecutable: "runghc",
  javaCompilerExecutable: "",
  javaExecutable: "java",
  graphvizExecutable: "dot",
  llvmInterpreterExecutable: "lli",
  ebpfClangExecutable: "clang",
  ebpfBpftoolExecutable: "bpftool",
  ebpfLlvmObjdumpExecutable: "llvm-objdump",
  ebpfIncludePaths: "",
  ebpfAllowKernelLoad: false,
  bpftraceExecutable: "bpftrace",
  leanExecutable: "lean",
  coqExecutable: "coqc",
  smtExecutable: "z3",
  writeOutputToNote: false,
  outputVisibleLines: 0,
  autoRunOnFileOpen: false,
  apiEnabled: false,
  apiHost: "127.0.0.1",
  apiPort: 27188,
  apiKeys: "",
  showCodeVisualizationButton: true,
  hashCodeBlocks: false,
  signingMode: "ssh",
  signingSignerId: "",
  signingPublicKey: "",
  signingPublicKeyPath: "",
  signingSshKeyPath: "",
  signingSshAuthSock: "",
  signingSshAllowedSigners: "",
  signingSshAllowedSignersPath: "",
  signingSshNamespace: "lotus-reproducibility@tzadikimctf.local",
  showObsidianContextWarning: true,
  extractedSourcePreviewMode: "collapsed",
  showLanguageCapabilityMetadata: true,
  languageConfigurationVersion: 3,
  enabledLanguagePacks: getDefaultLanguagePackIds(),
  enabledLanguages: getDefaultLanguageIds(),
  externalLanguagePacks: [],
  customLanguages: [],
  pdfExportMode: "code",
  htmlExportGraphAssetMode: "cdn",
  loggingEnabled: false,
  loggingGlobalTextEnabled: true,
  loggingGlobalTextPath: ".lotus/logs/events.log",
  loggingGlobalJsonlEnabled: true,
  loggingGlobalJsonlPath: ".lotus/logs/events.jsonl",
  loggingPerNoteTextEnabled: false,
  loggingPerNoteTextPathPattern: ".lotus/logs/notes/{note}.log",
  loggingPerNoteJsonlEnabled: false,
  loggingPerNoteJsonlPathPattern: ".lotus/logs/notes/{note}.jsonl",
  loggingProcessEnabled: false,
  loggingProcessCommand: "",
  loggingHttpEnabled: false,
  loggingHttpEndpoint: "",
  loggingHttpHeaders: "",
  loggingViewerJsonlPath: ".lotus/logs/events.jsonl",
  loggingRedactionRules: "",
  loggingNotePathMode: "hash",
  loggingMachineHashScope: "install",
  loggingIncludeCode: false,
  loggingIncludeOutput: false,
  loggingIncludeInput: false,
  loggingMaxEventBytes: 65536,
  loggingMachineId: "",
  defaultContainerGroup: "",
  godboltResolveCompilerFromApi: true,
  godboltCompilerDefaults: JSON.stringify(DEFAULT_GODBOLT_COMPILER_DEFAULTS, null, 2),
  godboltOptionsDefaults: JSON.stringify(DEFAULT_GODBOLT_OPTIONS_DEFAULTS, null, 2),
};
