name: Production Release

on:
  push:
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"
  workflow_call:
    inputs:
      tag:
        description: Release tag to publish
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag to publish
        required: true
        type: string


permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for smoke tests to succeed
        uses: lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc
        with:
          ref: ${{ github.sha }}
          check-regexp: '^smoke.*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          allowed-conclusions: success

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22
          cache: npm

      - run: npm ci --legacy-peer-deps

      - run: npm run build -- --production

      - name: Attest release assets
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373
        with:
          subject-path: |
            main.js
            manifest.json
            styles.css

      - name: Create Production Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with:
          tag_name: ${{ inputs.tag || github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            main.js
            manifest.json
            styles.css
